script "Global | GIT | Changes to be committed | New file | Menu"
--> MetaData
-
license: GPLv3
name: Global | GIT | Changes to be committed | New file | Menu
type: controller
version: 0.1

/*
Here you can describe this menu.
Full help text should be provided on the linked wiki.
*/

--> Variables
-
local LocalArray

--> Menu | Init
-


--> Global | GIT | Changes to be committed | New file | Menu
-
on menu_CommitChanges arrayView
   -- do the above
end menu_CommitChanges


--> Deps
-
